### ISSUE TITLE
Name conflict with existing VCS

### ISSUE THREAD

**Issue by Marie-Joseph** [gotvc/got#20]
https://gameoftrees.org/

I am not affiliated with and don't use got, but I thought you'd like to know.

**Comment by stspdotname** [comment]
Game of Trees author here. 

For the record, I do not have a problem with this. I don't feel like I "own" this name in any way. Authors should be able to freely choose a name for a work they produce.

There are practical concerns for end users, such as name collisions in directories like /usr/bin, which are unfortunate. But package managers can deal with this by marking the corresponding packages as conflicting. This is not really a problem for authors unless they aim for maximum reach of the product they produce (and yielding $$$), which I do not -- my target audience is limited, as stated on the web site; though my software is of course available to anyone who wants it due to the nature of the ISC license.

There are other existing name collisions with projects on Github. A quick search shows these two:
https://github.com/melbahja/got
https://github.com/sindresorhus/got

For reference, one of those has a similar issue filed: https://github.com/melbahja/got/issues/33

**Comment by brendoncarroll** [comment]
It seems like this is always going to happen for short names which are also common words.  That doesn't mean anyone should stop using short names for common tools that need to be typed often-like version control.  As @stspdotname mentioned, this is only a practical issue if the user bases overlap.
